name: Deploy static site to GitHub Pages

on:
  push:
    branches: ["main"]        # Trigger on pushes to main branch
  workflow_dispatch:           # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: (Optional) Build step if using a generator like React/Vue
      # Uncomment if you have a build process
      #- name: Install dependencies
      #  run: npm install
      #- name: Build site
      #  run: npm run build

      # Step 3: Upload static files
      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'   # Change this if your files are in a subfolder like ./dist or ./build

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
